---
deployment:
  tasks:
    - export DEPLOYPATH=/home/konilncu/public_html
    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='*.md' ./ $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/index.php